[formatting]
align_comments      = true
align_entries       = true
allowed_blank_lines = 1
array_auto_collapse = false
reorder_arrays      = true
reorder_keys        = true
trailing_newline    = true
