cask_args appdir: "/Applications"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

brew "autopep8"
brew "awscli"
brew "bash"
brew "black"
brew "cookiecutter"
brew "deno" # macOS-only
brew "ffmpeg"
brew "flake8"
brew "fx"
brew "gh"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "gnu-sed"
brew "go"
brew "grep"
brew "httpie"
brew "jq"
brew "jupyterlab"
brew "libfido2"
brew "macos-trash" # macOS-only
brew "mas" # macOS-only
brew "media-info"
brew "mkvtoolnix"
brew "mp4v2"
brew "mypy"
# brew "mysql-client"
brew "node"
brew "openssh"
brew "pinentry"
# brew "pinentry-mac"
brew "pipx"
brew "pnpm"
brew "postgresql@14"
brew "pre-commit"
brew "prettier"
brew "python"
brew "r"
brew "rust"
brew "shellcheck"
brew "shfmt"
brew "starship"
brew "terraform"
# brew "terraformer"
brew "typescript"
brew "webtorrent-cli"
brew "wrangler"
brew "ykman"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

cask "1password"
cask "alfred"
cask "backblaze"
cask "brave-browser"
# cask "datagrip"
cask "docker"
cask "firefox"
cask "handbrake"
# cask "inkscape"
cask "karabiner-elements"
cask "kitty"
cask "makemkv"
cask "plex-media-server"
# cask "postico"
# cask "postman"
cask "protonvpn"
# cask "rstudio"
# cask "visual-studio-code"
cask "vlc"
cask "vscodium"
cask "zotero" # no arm64_big_sur yet

# mas "1password", id: 1333542190
mas "bear", id: 1091189122
mas "cascadea", id: 1432182561
mas "daisydisk", id: 411643860
mas "duckduckgo privacy essentials", id: 1482920575
mas "keynote", id: 409183694
mas "numbers", id: 409203825
mas "pages", id: 409201541
mas "pdf expert", id: 1055273043
