#!/bin/bash
### ------------------ Bootstrap pre-installation script ------------------ ###
# Run by run_dotfile_scripts() in strap.sh

echo "### ------------------------ Important notes ------------------------ ###"
echo "-> Log in to Mac App Store to enable the mas cli."
echo "-> --debug is required for password prompt from script/strap-after-setup."
echo "### ----------------------------------------------------------------- ###"
