#!/usr/bin/env bash
### ----------------- Bootstrap post-installation scripts ----------------- ###
# Run by run_dotfile_scripts in bootstrap.sh

# Run scripts: scripts must be executable (chmod +x)
echo "-> Running scripts from script/strap-after-setup"

~/.dotfiles/script/symlink.sh

if command -v npm 1>/dev/null; then
  ~/.dotfiles/script/npm_globals.sh
else
  echo "npm not found. Skipping npm_globals.sh."
fi

if [ "$(uname -s)" = "Darwin" ]; then
  ~/.dotfiles/script/macos.sh
else
  echo "Not macOS. Skipping macos.sh."
fi

declare -a VSCODES
for i in {code,code-exploration,code-insiders,code-server,codium}; do
  if command -v "$i" >/dev/null 2>&1; then VSCODES+=("$i"); else continue; fi
done
if [ "$(whoami)" = "codespace" ]; then
  echo "Error: Codespaces VSCode CLI can't install extensions."
else
  ~/.dotfiles/script/codium_extensions.sh "${VSCODES[@]}"
fi

# Set shell
if ! [[ $SHELL =~ "zsh" ]] && command -v zsh >/dev/null 2>&1; then
  echo "-> Changing shell to Zsh. Password entry required."
  if [ "$(uname)" = "Linux" ]; then
    command -v zsh | sudo tee -a /etc/shells
    sudo chsh -s "$(command -v zsh)" "$USER"
  else
    chsh -s "$(command -v zsh)"
  fi
else
  echo "-> Shell is already set to Zsh."
fi

RAW="https://raw.githubusercontent.com"
# Install prompt
# zsh4humans and powerlevel10k
sh -c "$(curl -fsSL $RAW/romkatv/zsh4humans/v5/install)"

# Install Poetry: https://python-poetry.org/docs/
echo "-> Installing Poetry for Python packaging and dependency management"
curl -fsSL $RAW/python-poetry/poetry/master/get-poetry.py | python3 -
