#!/usr/bin/env bash
### ----------------- Bootstrap post-installation scripts ----------------- ###
# Run by run_dotfile_scripts in bootstrap.sh
# Scripts must be executable (chmod +x)
echo "-> Running strap-after-setup. Some steps may require password entry."
RAW="https://raw.githubusercontent.com"

### Configure macOS
if [ "${MACOS:-0}" -gt 0 ] || [ "$(uname)" = "Darwin" ]; then
  "$HOME"/.dotfiles/script/macos.sh
else
  echo "Not macOS. Skipping macos.sh."
fi

### Install user Python packages
if command -v python3 &>/dev/null && ! command -v poetry &>/dev/null; then
  export POETRY_HOME="$HOME/.local"
  curl -fsS -o "$HOME/install-poetry.py" \
    $RAW/python-poetry/poetry/HEAD/install-poetry.py
  python3 "$HOME/install-poetry.py"
else
  echo "Skipping Poetry install."
fi

### Install VSCode extensions
for i in {code,code-exploration,code-insiders,code-server,codium}; do
  if [ "${CODESPACE:-0}" -gt 0 ] || [ "$(whoami)" = "codespace" ]; then
    echo "Error: Codespaces VSCode CLI can't install extensions."
  else
    "$HOME"/.dotfiles/script/vscode-extensions.sh "$i"
  fi
done

### Set shell
if ! [[ $SHELL =~ "zsh" ]] && command -v zsh &>/dev/null; then
  echo "--> Changing shell to Zsh. Password entry required."
  [ "${LINUX:-0}" -gt 0 ] || [ "$(uname)" = "Linux" ] &&
    command -v zsh | sudo tee -a /etc/shells
  sudo chsh -s "$(command -v zsh)" "$USER"
else
  echo "Shell is already set to Zsh."
fi
if [ "${LINUX:-0}" -gt 0 ] ||
  [ "$(uname)" = "Linux" ] ||
  ! type brew &>/dev/null &&
  ! [ -d "$HOME/.zsh/pure" ]; then
  echo "--> Manually installing pure prompt."
  mkdir -p "$HOME/.zsh"
  git clone https://github.com/sindresorhus/pure.git "$HOME/.zsh/pure"
fi
