#!/bin/bash
### ------------------- Strap post-installation scripts ------------------- ###
# Run by run_dotfile_scripts() in strap.sh

# Run scripts: scripts must be executable (chmod +x)
echo "-> Running scripts from script/strap-after-setup"
~/.dotfiles/script/symlink.sh
~/.dotfiles/script/npm_globals.sh
[ "$(uname -s)" = "Darwin" ] && ~/.dotfiles/script/macos.sh

echo "-> Installing VSCode extensions"
CODE_DISTRO=${CODE_DISTRO:-"code"}
if [ "$(whoami)" = "codespace" ]; then
  echo "Error: Codespaces VSCode CLI can't install extensions."
else
  ~/.dotfiles/script/codium_extensions.sh "$CODE_DISTRO"
fi

# Install Poetry: https://python-poetry.org/docs/
echo "-> Installing Poetry for Python packaging and dependency management"
curl -fsSL \
  https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py |
  python -

# Create directory for Zsh shell functions
mkdir ~/.zfunc

# Set shell
if [ "$SHELL" != "/bin/zsh" ] && which zsh; then
  echo "-> Changing shell to Zsh. Password entry required."
  chsh -s /bin/zsh
fi
